version: '3.8'

services:
  app:
    image: otcheredev/sosbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_user # Replace with your DB user
      - DATABASE_PASSWORD=your_db_password # Replace with your DB password
      - DATABASE_NAME=your_db_name # Replace with your DB name

