version: '3.8'

services:
  app:
    image: otcheredev/sosbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=
      - JWT_SECRET=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_CLOUDNAME=
      - APP_ID=
      - AGORA_CERTIFICATE=
      - AGORA_ID=
